<p><strong>SET-UP INSTRUCTIONS:</strong><br />This is a computational text analysis on news articles. We use the following two external packages:<br /> - StanfordCore NLP (more info here: <a href="SET-UP%20INSTRUCTIONS: This is a computational text analysis on news articles. We use the following two external packages:   - StanfordCore NLP (more info here: https://stanfordnlp.github.io/CoreNLP/)   - XChart (https://knowm.org/open-source/xchart/)      Our analysis is set up as a maven roject, and therefore it is not necessary to download any .jar files.   In order to run the analysis, you will need to dowload all of the files in the Design MileStone Folder,    and set up the project as a maven project in your IDE of choice. (The pom.xml file is located here.)   More info on setting up Maven projects can be found here: http://maven.apache.org/guides/getting-started/      THE ANALYSIS - A BRIEF OVERVIEW:   ">https://stanfordnlp.github.io/CoreNLP/</a>)<br /> - XChart (<a href="https://knowm.org/open-source/xchart/">https://knowm.org/open-source/xchart/</a>)<br /> <br /> Our analysis is set up as a maven roject, and therefore it is not necessary to download any .jar files. In order to run the analysis, you will need to dowload all of the files in the Design MileStone Folder, and set up the project as a maven project in your IDE of choice. (The pom.xml file is located here.) More info on setting up Maven projects can be found here: <a href="https://knowm.org/open-source/xchart/">http://maven.apache.org/guides/getting-started/</a></p>
<p>&nbsp;</p>
<p><strong>THE NITTY-GRITTY - HOW THE ANALYSIS IS DESIGNED:</strong></p>
<p>//I'll put a more detailed breakdown of how thngs are structured here&nbsp;</p>
<p><br /> <br /> <strong>TLDR; THE ANALYSIS - A BRIEF OVERVIEW:</strong></p>
<p>In order to run the analysis, you'll need to run the ProjectRunnerClass. In the console, you will be asked whether or not you would like to create an .ser file from a sample of the full dataset. We have included this option so that you (the user, the TA, etc) can see our RawDocumentReader class in action. When this class is run on the full data set, it takes arond four hours, due to the computationally-intensive tasks of sentiment analysis and named-entity recognition.&nbsp;</p>
<p>After the (optional) ceation of the test .ser file, the full analysis will being to run. When it is complete, a bare-bones swing window will display the following graphs:</p>
<p>&nbsp;</p>
<p>//will list descriptions of the graphs here</p>
